### ISSUE TITLE
Cannot minimize a simple function

### ISSUE THREAD

**Issue by michellemay** [tobegit3hub/advisor#11]
I did a simple test to minimize x^2-3x+2 using BayesianOpt.

It seems incapable of minimizing.  It always maximize the function.
I can maximize the inverse of the function.

[examples.zip](https://github.com/tobegit3hub/advisor/files/2340039/examples.zip)

**Comment by andresmore** [comment]
BayesianOptimization is not taking into account the goal of the study, its always looking to maximize the objective value
https://github.com/tobegit3hub/advisor/blob/26cfd133e7476e543f571085d08a8087a093f40d/advisor_server/suggestion/algorithm/bayesian_optimization.py#L242-L248

**Comment by tobegit3hub** [comment]
Thanks for your report @michellemay and @andresmore 's comment 👍 

It is fixed now and we have test for min and max scenarios.

<img width="1440" alt="screen shot 2018-09-14 at 12 06 52 am" src="https://user-images.githubusercontent.com/2715000/45500991-9c59e980-b7b2-11e8-9ed8-6500e06b49db.png">

<img width="1440" alt="screen shot 2018-09-14 at 12 07 48 am" src="https://user-images.githubusercontent.com/2715000/45501032-b5fb3100-b7b2-11e8-9e2f-eecbde5f4a4d.png">
