### ISSUE TITLE
Hello! I have run four examples of advisor. I want to change the algorithm but there was a mistake

### ISSUE THREAD

**Issue by yemahei** [tobegit3hub/advisor#18]

**Comment by tobegit3hub** [comment]
Can you provide the configuration and logs about this issue? @yemahei

**Comment by yemahei** [comment]
I change advisor_client/examples/tensorflow_mnist /config.json  replace RandomSearch with HyperoptRandomSearch
 error:
Traceback (most recent call last):
  File "/usr/local/bin/advisor", line 11, in <module>
    load_entry_point('advisor', 'console_scripts', 'advisor')()
  File "/tmp/advisor_client/advisor_client/commandline/command.py", line 194, in main
    args.func(args)
  File "/tmp/advisor_client/advisor_client/commandline/command.py", line 131, in run_with_file
    launcher.run()
  File "/tmp/advisor_client/advisor_client/runner/runner_launcher.py", line 67, in run
    logging.info("Get trial: {}".format(trials[0]))
IndexError: list index out of range

**Comment by tobegit3hub** [comment]
Thanks for reporting @yemahei .

It is the bug of `HyperoptRandomSearch` and we got the error log in server side.

<img width="1440" alt="screenshot 2018-10-18 at 10 40 30 am" src="https://user-images.githubusercontent.com/2715000/47128057-57016e00-d2c2-11e8-8795-57674d6c3f56.png">

I will fix it soon and add more tests for that.

**Comment by tobegit3hub** [comment]
It is fixed after `0.1.6`. You can `pip install -U advisor` and `git pull` to use the latest code.

**Comment by yemahei** [comment]
nothing changed, The same kind of mistake. Do I need to change other parameters when I change the algorithm

**Comment by tobegit3hub** [comment]
It seems you used the old docker image. Please try `docker pull tobegit3hub/advisor` and start the server again.

I weill update the `advisor_admin` to pull the latest docker image to avoid this problem.
