### ISSUE TITLE
INTEGER out of bound

### ISSUE THREAD

**Issue by Earthson** [tobegit3hub/advisor#2]
I have parameter defined like:

```
        {
            "parameterName": "l1024",
            "type": "INTEGER",
            "minValue": 0,
            "maxValue": 2,
            "feasiblePoints": "",
            "scallingType": "LINEAR"
        },
```

but I got suggestion l1024 = 16

![image](https://user-images.githubusercontent.com/1193039/32095604-4add6614-bb36-11e7-9b72-de2fd2978ad2.png)

**Comment by tobegit3hub** [comment]
Thanks for reporting @Earthson 

The suggestion is right and the suggested "l1024" is "1". But the output is out-of-order. The "16" is for the parameter "l64".

**Comment by Earthson** [comment]
That's not correct, I'm sure the value received by python client is l1024=16.

The error always comes with BayesianOptimizizationTrial. like this:

```
        {
            "parameterName": "num_leaves",
            "type": "DISCRETE",
            "minValue": 0,
            "maxValue": 0,
            "feasiblePoints": "63, 127, 255",
            "scallingType": "LINEAR"
        },

```

![image](https://user-images.githubusercontent.com/1193039/32107502-5bf869c8-bb61-11e7-8224-c070fa782925.png)

**Comment by Earthson** [comment]
I'm using the docker image you given.

**Comment by tobegit3hub** [comment]
Please give the example of `l1024` and what I got here is `num_leaves`.

Everything works like what we expect. Are you sure the parameter name and result are consistent? @Earthson

**Comment by Earthson** [comment]
"But the output is out-of-order", what that means? The json I got is out of order? so how could I get a correct value of l1024?

**Comment by tobegit3hub** [comment]
According your json file and screenshot, your define the parameter `l1024` which should be integer from 0 to 1.

```
        {
            "parameterName": "l1024",
            "type": "INTEGER",
            "minValue": 0,
            "maxValue": 2,
            "feasiblePoints": "",
            "scallingType": "LINEAR"
        },
```

And look at the screenshot in ![](https://user-images.githubusercontent.com/1193039/32095604-4add6614-bb36-11e7-9b72-de2fd2978ad2.png) . 

Check out the id of `44`, the  value of `l1024` is `1`, which is totally what we expected.

**Comment by Earthson** [comment]
@tobegit3hub please chek out the id of 45, which is BayesianOptimizationTrial, got "l1024"=16. It's not a correct value

**Comment by tobegit3hub** [comment]
You're right. The returned values from id `45` is wrong.

But I'm not able to re-produce this problem. Can you try in the public advisor server http://hypertune.cn/ ? @Earthson

**Comment by codlife** [comment]
Hi @tobegit3hub @Earthson ,what's the python version, i use python3.5 ,which can't work. Thankyou！

**Comment by tobegit3hub** [comment]
Hi @codlife , can you open another issue and paste the error log about Python 3.5? I haven't test in Python 3.5 but it should work properly.

**Comment by tobegit3hub** [comment]
The import error is tracked in https://github.com/tobegit3hub/advisor/issues/3 now.

I will close this issue because we can not re-produce the issue. Feel free to re-open if having any problem.
