### ISSUE TITLE
storage backend

### ISSUE THREAD

**Issue by ibayer** [tobegit3hub/advisor#37]
Hi,
does advisor server have any way to persist trails to a storage back-end?

If such an option isn't available atm could you point me to the source code best suited to extend with such capabilities?

**Comment by tobegit3hub** [comment]
The data is stored in database, actually in sqlite from Django.

You may update the implementation of API server to store data in other storage or change the Django storage backend.

**Comment by ibayer** [comment]
@tobegit3hub 
Thanks for your answer. Changing the Django storage backend was straight forward. :-)
