### ISSUE TITLE
Sign in error

### ISSUE THREAD

**Issue by lk1983823** [tobegit3hub/advisor#8]
I follow your instruction to open http://127.0.0.1:8000 in the browser and sign in with my github. But it shows 404 error the page not found. 
When I use the command "pip install advisor_clients",  it shows "Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Forwarding failure',))': /simple/advisor-clients/"

Thank you!!

**Comment by tobegit3hub** [comment]
Thanks for reporting. In fact, you don't need to sign in with Github account. You can just click the button in the left top to access the dashboard page.

The problem of installing `advisor_cients` shows the `ProxyError`. You can check your proxy configuration or just disable command-line proxy with these commands.

```
export http_proxy=''
export https_proxy=''
```

**Comment by tobegit3hub** [comment]
Close because of no response.

Please re-open the issue if you have any other question.
