### ISSUE TITLE
Wrong order for bounds in Python 2.7

### ISSUE THREAD

**Issue by gaomochi** [tobegit3hub/advisor#9]
Hi, when using Advisor to get suggestion, i get wrong trial that the parameter was out of the range i set.
The study conf shows as below

{   maxTrails: 20,   randomInitTrail: 5,   params: [     {       scallingType: "LINEAR",       type: "INTEGER",       maxValue: 20,       minValue: 5,       parameterName: "max_depth",       feasiblePoints: ""     },     {       scallingType: "LINEAR",       type: "DOUBLE",       maxValue: 0.2,       minValue: 0,       parameterName: "eta",       feasiblePoints: ""     }   ],   goal: "MAXIMIZE" }

and i get a trial like this

{"eta": 19.999988873780502, "max_depth": 0}

then i found line 153 of bayesian_optimization.py  
`bound_dict = {}`
it's not in order as you insert in python 2.7 while iterating, so it may get wrong order when construct bounds array at line 182-184
```
for key in bound_dict.keys():
        bounds.append(bound_dict[key])
      bounds = np.asarray(bounds)
```
I think it's better to use 
`bound_dict = OrderedDict()`
to keep the order in bound_dict to get the right suggestion.

**Comment by tobegit3hub** [comment]
Thanks for reporting @gaomochi . I will have a look and fix it soon.

**Comment by tobegit3hub** [comment]
Thanks for reporting @gaomochi 👍 

This is fixed now and we add some unit tests for that.
